CREATE TABLE IF NOT EXISTS Users(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS Articles(
    id INTEGER PRIMARY KEY  AUTO_INCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    author INTEGER NOT NULL
);
